### ISSUE TITLE
Evaluation scripts

### ISSUE THREAD

**Issue by j-bac** [jzthree/quasildr#1]
Dear Mr. Zhou and Ms. Troyanskaya,
Many thanks for this work and your package!
I am interested in the scripts you used to load the data from dynverse and evaluate trajectory scores. Would you be willing to share those ?

**Comment by jzthree** [comment]
Hey you can find all relevant scripts including what you are looking for here https://github.com/jzthree/quasildr/tree/master/Manuscript . Feel free to use and you can email me if you have trouble using them jzhoup@gmail.com. We only ask you to avoid publishing work based on our code prior to our publication (which is under review).
